version: "3"

services:
    app:
        container_name: go-api
        build: 
            context: app
            dockerfile: Dockerfile
        volumes: 
            - ./app/:/app
        ports:
            - "3000:3000"
        depends_on:
            - data
        environment:
            WAIT_HOSTS: data:3306
        networks:
            - myapp

    data:
        container_name: data-mysql
        build: 
            context: data
            dockerfile: Dockerfile
        volumes: 
            - ./data:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "database"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - myapp

networks:
    myapp: